In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
matrix = np.array([[1, 2, 3, 4], [4, 5, 6, 5], [7, 8, 9, 5]])
print(matrix)


[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 5]]


In [5]:
zeros = np.zeros((3, 3))  
ones = np.ones((2, 2))   
eye = np.eye(3)           
print(zeros)
print(ones)
print(eye)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
ones = np.ones((2, 2)) 
print(ones)

[[1. 1.]
 [1. 1.]]


In [8]:
eye = np.eye(3) 
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [1]:
arr = np.arange(0, 50, 5)  # Array from 0 to 9 with step of 2
print(arr)

NameError: name 'np' is not defined

In [ ]:
arr = np.linspace(0, 50, 5)  
print(arr)


In [6]:
arr = np.array([1, 2, 3, 4])
print(arr + 2)  # Add 2 to each element
print(arr * 3)  # Multiply each element by 3


[3 4 5 6]
[ 3  6  9 12]


In [7]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

product = np.dot(matrix1, matrix2)
print(product)


[[19 22]
 [43 50]]


In [27]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])      # Access the second element
print(arr[0:3])    # Slice from the second to the fourth element


20
[10 20 30]


In [28]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2])   # Access the element at the second row, third column
print(matrix[2,:])   # Access all rows of the second column


6
[7 8 9]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))   # Mean
print(np.sum(arr))    # Sum
print(np.max(arr))    # Maximum
print(np.min(arr))    # Minimum
print(np.std(arr))    # Standard deviation


3.0
15
5
1
1.4142135623730951


In [11]:
arr = np.arange(1, 10)
reshaped = arr.reshape((3, 3))  # Reshape to 3x3 matrix
print(reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
transposed = reshaped.T
print(transposed)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
arr = np.array([1, 2, 3])
matrix = np.array([[1], [2], [3]])

result = arr + matrix
print(result)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [14]:
random_arr = np.random.rand(3, 3)  # 3x3 matrix with random values from [0, 1)
print(random_arr)

random_int_arr = np.random.randint(0, 10, (3, 3))  # 3x3 matrix with random integers from 0 to 9
print(random_int_arr)


[[0.04354263 0.90765938 0.67974755]
 [0.90230963 0.04194419 0.19479115]
 [0.1013152  0.09291469 0.69581315]]
[[0 4 2]
 [8 9 0]
 [3 7 5]]
